qemu-system-x86_64 -m 4096 -hda syzkaller.img --enable-kvm -net nic -kernel vmlinuz-4.14.0-rc5+ -append "root=/dev/mapper/rhel-root rd.lv=rhel/root" -net user,host=10.0.2.10,hostfwd=tcp::56788-:22 -initrd initramfs-4.14.0-rc5+.img

# uefi machines ...
/usr/libexec/qemu-kvm  -m 512M -net nic -net user,host=10.0.2.10,hostfwd=tcp::56788-:22 -display none -serial stdio -smp sockets=2,cores=2,threads=1  -enable-kvm  -hda /home/libvirt/rhel-7.5.qcow2  -vnc 0.0.0.0:1 -monitor telnet:127.0.0.1:1234,server,nowait -gdb tcp::1235 -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/test  -machine pc-q35-rhel7.5.0,accel=kvm,usb=off,dump-guest-core=off -cpu IvyBridge -drive file=/usr/share/OVMF/OVMF_CODE.secboot.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/var/lib/libvirt/qemu/nvram/rhel-7.5_VARS.fd,if=pflash,format=raw,unit=1

 /usr/libexec/qemu-kvm  -m 512M -net nic -net user,host=10.0.2.10,hostfwd=tcp::56788-:22 -display none -serial stdio -smp sockets=2,cores=2,threads=1  -enable-kvm  -hda /home/libvirt/rhel-7.5.qcow2  -vnc 0.0.0.0:1 -monitor telnet:127.0.0.1:1234,server,nowait -gdb tcp::1235 -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/test  -machine pc-q35-rhel7.5.0,accel=kvm,usb=off,dump-guest-core=off -cpu IvyBridge -drive file=/usr/share/OVMF/OVMF_CODE.secboot.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/var/lib/libvirt/qemu/nvram/rhel-7.5_VARS.fd,if=pflash,format=raw,unit=1 -kernel /home/chuhu/Git/rhel7/arch/x86/boot/bzImage  -append "root=/dev/mapper/rhel-root rd.lv=rhel/root earlyprintk=serial console=ttyS0" --initrd /boot/initramfs-3.10.0-862.el7.x86_64.img 

 /usr/libexec/qemu-kvm  -m 512M -net bridge,br=switch -net nic,model=virtio -display none -serial stdio -smp sockets=2,cores=2,threads=1  -enable-kvm  -hda /home/libvirt/rhel-7.5.qcow2  -vnc 0.0.0.0:1 -monitor telnet:127.0.0.1:1234,server,nowait -gdb tcp::1235 -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/test  -machine pc-q35-rhel7.5.0,accel=kvm,usb=off,dump-guest-core=off -cpu IvyBridge -drive file=/usr/share/OVMF/OVMF_CODE.secboot.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/var/lib/libvirt/qemu/nvram/rhel-7.5_VARS.fd,if=pflash,format=raw,unit=1 

virt-install --machine q35 --cpu host-passthrough --name chuhu --mac 52:55:00:00:00:00 --location http://download/x86_64/os/ --ram=2048 --vcpus=4 --file-size=20 --hvm --nonsparse --debug --accelerate --os-variant=virtio26 --network bridge:br1 --serial file,path=/mnt/logs/x86_64_kvm_2cpu_console.log --serial pty --console pty --file /home/virtimages/VirtualMachines/x86_64_kvm_4cpu.img --extra-args "inst.ks=http://server/kickstart/8421428 serial console=tty0 console=ttyS0,115200 " --noreboot --vnc --network network=default
